name: Create release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSVC environment
        uses: microsoft/setup-msbuild@v1

      - name: Set up NuGet CLI
        run: Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile C:\Windows\nuget.exe

      - name: Install packages
        run: nuget restore .\ReservedCpuSets\ReservedCpuSets.sln

      - name: Build executable
        run: |
          MSBuild.exe .\ReservedCpuSets\ReservedCpuSets.sln -p:Configuration=Release -p:Platform=x64
          MSBuild.exe .\ReservedCpuSetsDLL\ReservedCpuSets.sln -p:Configuration=Release -p:Platform=x64

      - name: Create folder structure
        run: |
          mkdir release\ReservedCpuSets
          move .\ReservedCpuSets\ReservedCpuSets\bin\x64\Release\ReservedCpuSets.exe release\ReservedCpuSets
          move .\ReservedCpuSetsDLL\x64\Release\ReservedCpuSets.dll release\ReservedCpuSets

      - name: Zip limit-nvpstate
        run: Compress-Archive -Path release\ReservedCpuSets -DestinationPath ReservedCpuSets.zip

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: ReservedCpuSets.zip
